export const listCountryCodes = [
    {value: '61', label: 'Australia (+61)'},
    {value: '43', label: 'Austria (+43)'},
    {value: '32', label: 'Belgium (+32)'},
    {value: '86', label: 'China (+86)'},
    {value: '45', label: 'Denmark (+45)'},
    {value: '33', label: 'France (+33)'},
    {value: '49', label: 'Germany (+49)'},
    {value: '852', label: 'Hong Kong (+852)'},
    {value: '91', label: 'India (+91)'},
    {value: '353', label: 'Ireland (+353)'},
    {value: '972', label: 'Israel (+972)'},
    {value: '39', label: 'Italy (+39)'},
    {value: '81', label: 'Japan (+81)'},
    {value: '60', label: 'Malaysia (+60)'},
    {value: '31', label: 'Netherlands (+31)'},
    {value: '64', label: 'New Zealand (+64)'},
    {value: '47', label: 'Norway (+47)'},
    {value: '48', label: 'Poland (+48)'},
    {value: '351', label: 'Portugal (+351)'},
    {value: '65', label: 'Singapore (+65)'},
    {value: '34', label: 'Spain (+34)'},
    {value: '46', label: 'Sweden (+46)'},
    {value: '41', label: 'Switzerland (+41)'},
    {value: '886', label: 'Taiwan (+886)'},
    {value: '66', label: 'Thailand (+66)'},
    {value: '44', label: 'United Kingdom (+44)'},
    {value: '1', label: 'US/Canada (+1)'},
  ];